server:
  port: 8094
  servlet:
    context-path: /amadeus
 

spring:
  datasource:
    url: jdbc:sqlserver://SINAZEDEV18;instanceName=SmartPRA_QA;portNumber=1433;user=qasmartpra;password=Tqrmdp234$#@!
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver   
  jpa:
    show-sql: false
    properties:
      hibernate:
        default_schema: smartpraflown_stg
        dialect: org.hibernate.dialect.SQLServer2012Dialect
        
    hibernate:
      ddl-auto: none   
       
  batch:
    job:
      enabled: false 
    tablePrefix : SmartPRAGlobalBatch.BATCH_
       
eureka:    
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8061/eureka      
      
feign:
  client:
    config:
      default:
        connectTimeout: 160000000
        readTimeout: 160000000 
        
