eureka:    
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://10.245.240.54:8061/eureka
      
spring:
  rabbitmq:
    host: 10.245.240.54
    port: 5672
    username: admin
    password: admin

