spring:
  datasource:
    url: jdbc:sqlserver://SINAZEDEV18;instanceName=SmartPRA_QA;portNumber=1433;user=qasmartpra;password=Tqrmdp234$#@!
    
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://10.245.240.63:8061/eureka
              