server:
  port: 8002
  servlet:
    context-path: /sales-validation
 

spring:
  datasource:
    url: jdbc:sqlserver://SINAZEDEV17;instanceName=SmartPRA_DEV;portNumber=1433;user=devsmartpra;password=Rtsneftimp@423!#
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver   
  jpa:
    show-sql: true
    properties:
      hibernate:
        default_schema: SmartPRASales_Stg
        dialect: org.hibernate.dialect.SQLServer2012Dialect
        
    hibernate:
      ddl-auto: none   
       
  batch:
    job:
      enabled: false 
    tablePrefix : SmartPRAGlobalBatch.BATCH_
       
eureka:    
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8061/eureka      
      
feign:
  client:
    config:
      default:
        connectTimeout: 160000000
        readTimeout: 160000000 
max-threads: 1    
batch-input-dir: /opt/smartpra/bsp/input   
        