server:
  port: 8097
  servlet:
    context-path: /misc-billing-global

 
      
spring:
  datasource:
    url: jdbc:sqlserver://SINAZEDEV17;instanceName=SmartPRA_DEV;portNumber=1433;user=devsmartpra;password=Rtsneftimp@423!#
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver     
  jpa:
    hibernate:
     ddl-auto: none 
    show-sql: true
    properties:
      hibernate:
       default_schema: miscbilling
       dialect: org.hibernate.dialect.SQLServer2012Dialect    

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8061/eureka

feign:
  client:
    config:
      default:
        connectTimeout: 160000000
        readTimeout: 160000000
        
      
            
      
    
  



